feat: add public cloud credential resource
Leaseweb/terraform-provider-leaseweb pull request #107
Opened 2024-10-18 11:56 UTC by majidkarimizadeh

#### NOTE:
we need to decide about `utils.Error` function, for now I just moved it around to be able to use it for dedicated server and public cloud.

2024-10-23 08:48 UTC, alrayyes requested changes

2024-10-23 08:48 UTC, alrayyes commented on internal/provider/provider_test.go
> +							"695ddd91-051f-4dd6-9120-938a927a47d0",
What happens if a user inputs an invalid instance id?

2024-10-23 08:48 UTC, alrayyes commented on internal/provider/provider_test.go
> +	   	password = "12341234"
Just double checking, are there validation rules for passwords server side?

2024-10-23 08:48 UTC, alrayyes commented on internal/provider/provider_test.go
> +	   	username = "root"
What happens when a user inputs a non existent user?

2024-10-23 08:48 UTC, alrayyes commented on internal/provider/provider_test.go
> +				// Update and Read testing
I'm guessing that because this is a credential importing is not possible?

2024-10-23 08:48 UTC, alrayyes commented on internal/provider/publiccloud/resource_credential.go
> +type credentialResourceData struct {
We need to come to an agreement as to what to name the model structs. Personally I like `resourceModelResource` as the prefix makes it clear what this is supposed to be. I think we should discuss this in a call so we're all on the same page.

2024-10-23 08:48 UTC, alrayyes commented on internal/provider/publiccloud/resource_credential.go
> +				Description: `The ID of the instance.`,
The validation rules should be added to the description. I would to publiccloud to understand what the rules for these are. I assume for example that you can't create credentials for an instance that's stopped?

2024-10-23 08:48 UTC, alrayyes commented on internal/provider/publiccloud/resource_credential.go
> +				Description: `The type of the credential. Valid options are: "OPERATING_SYSTEM", "CONTROL_PANEL"`,
Is there a publicCloud.Credential enum you can use here? Then you can be 100% sure that the documentation is correct in the future.

2024-10-23 08:48 UTC, alrayyes commented on internal/provider/publiccloud/resource_credential.go
> +				Description: `The password for the credentials`,
I forgot what it's called, but I believe there is an attribute for secret data like this so the password isn't echoed to the user console or logged.

2024-10-23 08:48 UTC, alrayyes commented on internal/provider/publiccloud/resource_credential.go
> +	opts := publicCloud.NewStoreCredentialOpts(
It would be better to have this logic in a resource method. Easy to understand & test.

2024-10-23 08:48 UTC, alrayyes commented on internal/provider/publiccloud/resource_credential.go
> +		summary := fmt.Sprintf("Error creating credential with username: %q and instance_id: %q", data.Username.ValueString(), data.InstanceID.ValueString())
At some point we need a style guide for error messages.

2024-10-23 08:48 UTC, alrayyes commented on internal/provider/publiccloud/resource_credential.go
> +		tflog.Error(ctx, fmt.Sprintf("%s %s", summary, utils.NewError(response, err).Error()))
You can use the logging function in utils for this. Handles a lot of this for you.

2024-10-23 11:03 UTC, imtiazPabel commented on internal/provider/publiccloud/resource_credential.go
> +type credentialResourceData struct {
IMHO, nice to be `credentialResourceModel` as terraform documentation have example. 
https://developer.hashicorp.com/terraform/tutorials/providers-plugin-framework/providers-plugin-framework-resource-create#implement-resource-data-models

But, of course, could be anything else, if team wants to decide.

2024-10-23 12:02 UTC, imtiazPabel commented on internal/provider/publiccloud/resource_credential.go
> +		tflog.Error(ctx, fmt.Sprintf("%s %s", summary, utils.NewError(response, err).Error()))
You are right. Nice to have logging in the same abstraction. Since we're gonna work later for error logging, at that time, maybe a lot of things gonna change, it's also fine to keep it like that.

2024-10-24 12:18 UTC, majidkarimizadeh commented on internal/provider/publiccloud/resource_credential.go
> +				Description: `The password for the credentials`,
added.

2024-10-24 12:19 UTC, alrayyes commented on internal/provider/publiccloud/resource_credential.go
> +		tflog.Error(ctx, fmt.Sprintf("%s %s", summary, utils.NewError(response, err).Error()))
That's fine. But then at least add a TODO

2024-10-25 07:31 UTC, majidkarimizadeh commented on internal/provider/provider_test.go
> +	   	password = "12341234"
they are, although I also added rule to check the length

2024-10-25 07:31 UTC, majidkarimizadeh commented on internal/provider/provider_test.go
> +	   	username = "root"
server side validation will take care of that

2024-10-25 09:04 UTC, majidkarimizadeh commented on internal/provider/provider_test.go
> +				// Update and Read testing
AFAIK no!

2024-10-25 09:29 UTC, majidkarimizadeh commented on internal/provider/publiccloud/resource_credential.go
> +		tflog.Error(ctx, fmt.Sprintf("%s %s", summary, utils.NewError(response, err).Error()))
for logging, we need to discuss more, we need to show details of error message though!

2024-10-25 09:48 UTC, majidkarimizadeh commented on internal/provider/publiccloud/resource_credential.go
> +		tflog.Error(ctx, fmt.Sprintf("%s %s", summary, utils.NewError(response, err).Error()))
btw TODO added.

2024-10-25 09:50 UTC, majidkarimizadeh commented on internal/provider/publiccloud/resource_credential.go
> +				Description: `The ID of the instance.`,
It will be handled by server side validation

2024-10-25 09:52 UTC, majidkarimizadeh commented on internal/provider/publiccloud/resource_credential.go
> +	opts := publicCloud.NewStoreCredentialOpts(
it's ONLY been used in here, no need to separate and move the login IMO!

2024-10-25 10:44 UTC, alrayyes requested changes

2024-10-25 10:44 UTC, alrayyes commented on internal/provider/provider_test.go
> +							`Attribute type value must be one of: \["OPERATING_SYSTEM" "CONTROL_PANEL"\],(\s*)got: "invalid"`,
Here it's better to just check for `Attribute type value must be one of:`. This way you don't need to refactor this test every time a type is added.

2024-10-25 10:44 UTC, alrayyes commented on internal/provider/publiccloud/credential_resource.go
> +			"username": schema.StringAttribute{
If you want to check for an empty string here as well, but it's not a dealbreaker.

2024-10-25 10:44 UTC, alrayyes commented on internal/provider/publiccloud/credential_resource.go
> +				Description: `The type of the credential. Valid options are: "OPERATING_SYSTEM", "CONTROL_PANEL"`,
You can keep the documentation up to date by copying & using the helper in https://github.com/Leaseweb/terraform-provider-leaseweb/blob/1fd8e45c1f1db1714a81f30d88f2d104b259fa92/internal/provider/publiccloud/credential_data_source.go#L72.

2024-10-25 10:44 UTC, alrayyes commented on internal/provider/publiccloud/credential_resource.go
> +	if resp.Diagnostics.HasError() {
This can be removed as you're already at the end of the function

2024-10-25 10:44 UTC, alrayyes commented on internal/provider/publiccloud/credential_resource.go
> +	if resp.Diagnostics.HasError() {
This can be removed.

2024-10-25 11:16 UTC, alrayyes approved these changes

2024-10-25 11:19 UTC, arunvarghe approved these changes

2024-10-25 11:19 UTC, imtiazPabel approved these changes

2024-10-25 11:20 UTC, merged