Implement publiccloud image datasource
Leaseweb/terraform-provider-leaseweb pull request #108
Opened 2024-10-21 10:25 UTC by alrayyes

2024-10-22 09:46 UTC, imtiazPabel commented on internal/provider/publiccloud/images_datasource.go
> +	_ datasource.DataSourceWithConfigure = &ImagesDataSource{}
I believe you forgot to add the interface `datasource.DataSource`
I couldn't find the struct as exported, if i'm right, then it should be `imagesDataSource`

2024-10-22 09:48 UTC, alrayyes commented on internal/provider/publiccloud/images_datasource.go
> +	_ datasource.DataSourceWithConfigure = &ImagesDataSource{}
On purpose. `DataSourceWithConfigure` already includes `DataSource` interface.

2024-10-22 09:50 UTC, imtiazPabel commented on internal/provider/publiccloud/images_datasource.go
> +	Id           types.String `tfsdk:"id"`
My understanding says, `ID` instead of `Id` is the go recommendation. There was a discussion about it, here you can get it https://github.com/Leaseweb/terraform-provider-leaseweb/pull/78#discussion_r1771109552

2024-10-22 09:54 UTC, alrayyes commented on internal/provider/publiccloud/images_datasource.go
> +	Id           types.String `tfsdk:"id"`
I don't care. If we're going with ID I'll make it ID. But let's do that in another PR. I'll update all ID references in publiccloud.

2024-10-22 10:00 UTC, imtiazPabel commented on internal/provider/publiccloud/images_datasource.go
> +func newDataSourceModelImageFromImage(sdkImage publicCloud.Image) dataSourceModelImage {
The name of the method more make sense to me `mapSDKImageToDataSourceImage / buildDataSourceImageFromSDKImage` or could be anything which is more readable. But `new` prefix doesn't sounds fit to me.

2024-10-22 10:06 UTC, imtiazPabel commented on internal/provider/publiccloud/images_datasource.go
> +		Id:      basetypes.NewStringValue(sdkImage.Id),
What if, we use the abstraction `sdkImage.GetId()`
Abstraction is doing some checks for us. Does it sounds helpful to you?

2024-10-22 10:07 UTC, imtiazPabel commented on internal/provider/publiccloud/images_datasource.go
> +func newDataSourceModelImageFromImageDetails(
Same opinion for this and rest of the other methods from me.
https://github.com/Leaseweb/terraform-provider-leaseweb/pull/108/files#r1810408150

2024-10-22 10:18 UTC, imtiazPabel commented on internal/provider/publiccloud/images_datasource.go
> +		State:        utils.AdaptNullableStringToStringValue(sdkImageDetails.State.Get()),
I think, that's how, you don't need to call a differnt method
basetypes.NewStringValue(sdkImageDetails.State.GetState())

2024-10-22 10:32 UTC, imtiazPabel commented on internal/provider/publiccloud/images_datasource_test.go
> +func Test_newDataSourceModelImageFromImage(t *testing.T) {
IMHO, I couldn't find the test brings any value. It's all about you're repeating the implementation also on test and checking my repeating is right or not.

2024-10-22 10:40 UTC, imtiazPabel commented on internal/provider/publiccloud/images_datasource.go
> +		Region:       utils.AdaptNullableStringEnumToStringValue(sdkImageDetails.Region.Get()),
If it's enough to use `basetypes.NewStringValue(sdkImageDetails.GetRegion())`, then we can also remove the utils method

2024-10-22 10:43 UTC, imtiazPabel commented on internal/provider/publiccloud/images_datasource.go
> +	_ datasource.DataSourceWithConfigure = &ImagesDataSource{}
You are completely right. IDK, why I didn't check it and always use both of the interface 🤪

2024-10-25 08:12 UTC, majidkarimizadeh commented
pls reflect the architecture, then LGTM!

2024-10-25 08:15 UTC, majidkarimizadeh requested changes
pls reflect the architecture, then LGTM!

2024-10-25 10:37 UTC, majidkarimizadeh approved these changes

2024-10-25 10:46 UTC, arunvarghe approved these changes

2024-10-25 10:57 UTC, imtiazPabel commented on internal/provider/publiccloud/images_data_source.go
> +type dataSourceModelImage struct {
Wouldn't it be `imageDataSourceModel`?

https://github.com/Leaseweb/terraform-provider-leaseweb/blob/main/ARCHITECTURE.md?plain=1#L26

2024-10-25 10:59 UTC, imtiazPabel approved these changes

2024-10-25 10:59 UTC, merged