feat: implement public cloud isos data source
Leaseweb/terraform-provider-leaseweb pull request #188
Opened 2024-11-29 06:36 UTC by arunvarghe

2024-11-29 08:27 UTC, alrayyes requested changes
Small nitpick

2024-11-29 08:27 UTC, alrayyes commented on internal/provider/publiccloud/isos_data_source.go
> +		summary := fmt.Sprintf("Reading data %s", i.name)
I would get rid of the summary variable as it adds nothing and use `fmt.Sprintf` statement itself as a parameter for `utils.Error`

2024-11-29 09:16 UTC, alrayyes approved these changes

2024-11-29 10:51 UTC, imtiazPabel commented on internal/provider/publiccloud/isos_data_source.go
> +	Isos []isoDataSourceModel `tfsdk:"isos"`
`iso` is an acronym.
In that case, should be all capital letter `ISO`, like `ID` which recommended by `GO`.
Same goes for the method name as well.

2024-11-29 10:55 UTC, imtiazPabel commented
I’m a bit skeptical about using the word `isos` as a data source name. 
I understand it’s likely used for pluralization, but I feel it would be worth quickly checking with the team before merging or releasing to see if they’re comfortable with it.

2024-11-29 10:58 UTC, alrayyes commented
> I’m a bit skeptical about using the word `isos` as a data source name. I understand it’s likely used for pluralization, but I feel it would be worth quickly checking with the team before merging or releasing to see if they’re comfortable with it.

What else do you want to call it? Naming convention is `ISO` in capitals. Multiple of ISO is ISOs. The whole reason we having naming conventions is to keep things simple.

2024-11-29 11:08 UTC, imtiazPabel commented
> > I’m a bit skeptical about using the word `isos` as a data source name. I understand it’s likely used for pluralization, but I feel it would be worth quickly checking with the team before merging or releasing to see if they’re comfortable with it.
> 
> What else do you want to call it? Naming convention is `ISO` in capitals. Multiple of ISO is ISOs. The whole reason we having naming conventions is to keep things simple.

You're right, by principal it's correct.
But sounds a bit weird to me (might be only to me) , so that, just recommended for a double-checking with other team member.

2024-11-29 11:16 UTC, alrayyes commented
> > > I’m a bit skeptical about using the word `isos` as a data source name. I understand it’s likely used for pluralization, but I feel it would be worth quickly checking with the team before merging or releasing to see if they’re comfortable with it.
> > 
> > 
> > What else do you want to call it? Naming convention is `ISO` in capitals. Multiple of ISO is ISOs. The whole reason we having naming conventions is to keep things simple.
> 
> You're right, by principal it's correct. But sounds a bit weird to me (might be only to me) , so that, just recommended for a double-checking with other team member.

Once you start using these acronyms things start to sound weird, that's just the way it is. A lot of variable naming in golang sounds weird.

2024-12-02 09:06 UTC, alrayyes requested changes

2024-12-02 09:06 UTC, alrayyes commented on internal/provider/publiccloud/isos_data_source.go
> +	var ISOs []publiccloud.Iso
this should lowercase as `ISO` is never exported. So `isos`

2024-12-03 08:46 UTC, merged