feat: implement dedicated server data source
Leaseweb/terraform-provider-leaseweb pull request #37
Opened 2024-08-09 11:12 UTC by majidkarimizadeh

2024-08-09 11:30 UTC, alrayyes requested changes
Looks good, a few small things & missing acceptance tests.

2024-08-09 11:30 UTC, alrayyes commented on .env.dist
>  #PUBLIC_CLOUD_API_SPEC_URL=http://host.docker.internal:8081/publicCloud.json
The url for local development should be added here

`#DEDICATED_SERVER_API_SPEC_URL=http://host.docker.internal:8081/dedicatedServer.json`

2024-08-09 11:30 UTC, alrayyes commented on .gitignore
> +docker-compose.override.yml
override doesn't exist (yet)

2024-08-09 11:30 UTC, alrayyes commented on internal/core/domain/dedicated_server/dedicated_server.go
> +	dedicatedServer := DedicatedServer{Id: id}
Id could be a value object. We only allow strings comprised of integers here.

2024-08-09 11:30 UTC, alrayyes commented on internal/core/domain/dedicated_server/dedicated_servers.go
> +type DedicatedServers []DedicatedServer
Nice!

2024-08-09 11:30 UTC, alrayyes commented on internal/core/ports/dedicated_server_repository.go
> +	// GetAllDedicatedServers Retrieve all dedicated_servers from the dedicated server api.
This should be a proper sentence. So `GetAllDedicatedServers retrieves all dedicated_servers from the deciated server api.`.

This is how all the go documentation is written.

2024-08-09 11:30 UTC, alrayyes commented on internal/core/services/dedicated_server/service.go
> +func (srv Service) GetAllDedicatedServers(ctx context.Context) (
I don't know what the best practice is but I like to return nil if an error is found. `GetAllDedicatedServers(ctx context.Context) (*domain.DedicatedServers, *errors.ServiceError)`

This way it's clear that dedicatedServers is not set.

2024-08-09 11:30 UTC, alrayyes commented on internal/core/services/dedicated_server/service.go
> +func (srv Service) GetAllDedicatedServers(ctx context.Context) (
Then you can just `return nil, *err`

2024-08-09 11:30 UTC, alrayyes commented on internal/facades/dedicated_server/data_adapters/to_data_source_model/adapter.go
> +		dedicated_server := adaptDedicatedServer(domainDedicatedServer)
I don't know what best practice is in golang, this or `dedicatedServer` for variable names.

2024-08-09 11:36 UTC, majidkarimizadeh commented on internal/facades/dedicated_server/data_adapters/to_data_source_model/adapter.go
> +		dedicated_server := adaptDedicatedServer(domainDedicatedServer)
missed this one, will change it to `dedicatedServer`

2024-08-09 11:37 UTC, majidkarimizadeh commented on .gitignore
> +docker-compose.override.yml
it does exist on my system, so just ignored it

2024-08-13 10:27 UTC, imtiazPabel commented on internal/provider/data_sources/dedicated_server/dedicated_servers/read.go
> +	state := dedicatedSeervers
I believe that's typo

2024-08-13 10:38 UTC, imtiazPabel commented on internal/repositories/dedicated_server_repository/dedicated_server_repository.go
> +		50, // metadata.GetLimit(),
Curious minds want to know, any specific reason to set the value 50?

2024-08-13 11:36 UTC, majidkarimizadeh commented on internal/repositories/dedicated_server_repository/dedicated_server_repository.go
> +		50, // metadata.GetLimit(),
with the default limit we face `timeout`, that's why I hard coded to 50, we need to remove the hard coded part later on.

2024-08-13 11:38 UTC, alrayyes commented on internal/core/ports/dedicated_server_repository.go
> +	// GetAllDedicatedServers Retrieve all dedicated_servers from the dedicated server api.
typo: Retrieve := retrieves

2024-08-13 11:39 UTC, alrayyes approved these changes

2024-08-13 11:41 UTC, merged