[WIP] feat: added server attributes in leaseweb_dedicated_server
Leaseweb/terraform-provider-leaseweb pull request #41
Opened 2024-08-16 09:53 UTC by majidkarimizadeh

2024-08-16 09:58 UTC, alrayyes commented
I know, work in progress. it's best practice to use [imperative tense verbs](https://github.com/conventional-commits/conventionalcommits.org/issues/84).  Ie: `add server attributes to ....` instead of `added server attributes to....`

2024-08-19 10:50 UTC, majidkarimizadeh commented
Working on tests

2024-08-20 11:51 UTC, alrayyes requested changes
Small stuff

2024-08-20 11:51 UTC, alrayyes commented on internal/core/domain/dedicated_server/cpu.go
> +func NewCpu(quantity int32, Type string) Cpu {
Everywhere else we use int64. I don't really care tbh but we should all use the same thing and write up some coding standards.

2024-08-20 11:51 UTC, alrayyes commented on internal/core/domain/dedicated_server/feature_availability.go
> +package dedicated_server
I know you copied this from me, but it's incorrect https://go.dev/blog/package-names

2024-08-20 11:51 UTC, alrayyes commented on internal/core/domain/dedicated_server/dedicated_server.go
> +func NewDedicatedServer(
No tests? Rinse & repeat for the other functions.

2024-08-20 11:51 UTC, alrayyes commented on internal/core/domain/dedicated_server/port.go
> +	Port string
Could you double check that this is a string in the actual api response?

2024-08-20 11:51 UTC, alrayyes commented on internal/facades/dedicated_server/data_adapters/to_data_source_model/adapter.go
> +	dedicatedServer := model.DedicatedServer{
You may as well do `return model.DedicatedServer{` here.

2024-08-20 11:51 UTC, alrayyes commented on internal/facades/dedicated_server/data_adapters/to_data_source_model/adapter_test.go
> +	assert.Equal(t, true, got.Automation.ValueBool())
Try to mix it up. This test won't catch a typo in the code as everything is true.

2024-08-20 11:51 UTC, alrayyes commented on internal/facades/dedicated_server/data_adapters/to_data_source_model/adapter_test.go
> +	assert.Equal(t, true, got.IpmiReboot.ValueBool())
you can use `assert.True(t, got.ImpiReboot.ValueBool())` here

2024-08-20 11:51 UTC, alrayyes commented on internal/facades/dedicated_server/data_adapters/to_data_source_model/adapter_test.go
> +	remote := domain.NewNetworkInterface("remote", "ip", "gateway", "loc_id", true, ports)
To save time in the future it's better to use `remote := domain.NetworkInterface(remote: "remote")` here. Now if `NewNetworkInterface` function changes you also have to update every single test that references it.

2024-08-20 11:51 UTC, alrayyes commented on internal/facades/dedicated_server/data_adapters/to_data_source_model/adapter_test.go
> +	assert.Equal(t, "id1", got.DedicatedServers[0].Id.ValueString())
It's a good idea to do `assert.Len(t, 2, got.DedicatedServers)` above

2024-08-20 11:51 UTC, alrayyes commented on internal/provider/data_sources/dedicated_server/dedicated_servers/schema.go
> +											Computed:    true,
These descriptions are pointless if you ask me. It's fairly obvious to anyone that every attribute is `The x of y". This description adds 0 value and is just something else to maintain every time the API definitions change.

2024-08-20 11:51 UTC, alrayyes commented on internal/provider/data_sources/dedicated_server/dedicated_servers/schema.go
> +														Description: "The Name of power port",
For this type of thing which comes back again and again it's a good idea to create a function. ie `portSchema()` and call that instead. That way there's one place to change if the schema changes for whatever reason.

2024-08-20 11:51 UTC, alrayyes commented on internal/repositories/dedicated_server_repository/data_adapters/to_domain_entity/adapter_test.go
> +	assert.Equal(t, "id", got.Id)
If you want to make this easy to read consider the following:

```go
want := domain.NewRack("id", "cap", "type")

assert.Equal(t, want, got)
```

This way the tests are bit easier to read, and if you add models to the domain entity, you will automatically have to add the tests here as the `NewRack` function will change.

2024-08-20 11:51 UTC, alrayyes commented on internal/repositories/dedicated_server_repository/data_adapters/to_domain_entity/adapter_test.go
> +	pciCard1 := dedicatedServer.NewPciCard()
What happens if this is null?

2024-08-20 11:51 UTC, alrayyes commented on internal/repositories/dedicated_server_repository/dedicated_server_repository.go
> +			dedicatedServers = append(dedicatedServers, dedicatedServer)
You can probably just do `dedicatedServers = append(dedicatedServers, p.adapDedicatedServer(sdkDedicatedServer))` here

2024-08-20 12:00 UTC, majidkarimizadeh commented on internal/core/domain/dedicated_server/feature_availability.go
> +package dedicated_server
What would you suggest?! `ds`? `dedicatedserver`? `dedicatedsrv`? `dsrv`? `srv`?

2024-08-20 12:03 UTC, majidkarimizadeh commented on internal/core/domain/dedicated_server/cpu.go
> +func NewCpu(quantity int32, Type string) Cpu {
I see we also use int32 in pagination and autoscaling group tests and ...! then we should change them too, I believe

2024-08-20 12:16 UTC, alrayyes commented on internal/core/domain/dedicated_server/cpu.go
> +func NewCpu(quantity int32, Type string) Cpu {
I don't really care what we use, we just all have to do the same thing. I chose int64 because Terraform (If I remember correctly), didn't support int32.

Upsides if int64:
- You can store bigger number

Downsides:
- Uses more memory

I'd say just go with int. It should automatically be set to int32/int64 [depending on the platform](https://go.dev/tour/basics/11). So golang would treat it as an int64 on 99.999999% of machines.

2024-08-20 12:16 UTC, alrayyes commented on internal/core/domain/dedicated_server/feature_availability.go
> +package dedicated_server
I like `dedicatedServer`. No need to to use abbreviations if we don't have to.

2024-08-20 12:20 UTC, majidkarimizadeh commented on internal/core/domain/dedicated_server/feature_availability.go
> +package dedicated_server
again, `dedicatedServer` is a bad idea! https://go.dev/blog/package-names

2024-08-20 12:21 UTC, majidkarimizadeh commented on internal/core/domain/dedicated_server/cpu.go
> +func NewCpu(quantity int32, Type string) Cpu {
then I'll change it to `int`

2024-08-20 12:33 UTC, alrayyes commented on internal/core/domain/dedicated_server/feature_availability.go
> +package dedicated_server
Oh yeah, that's right. I guess `dedicatedserver` then. Whatever you choose, it's probably a good idea to add something to the README or add a `DEVELOPMENT.md` to explain coding standards.

2024-08-20 12:34 UTC, alrayyes commented on internal/core/domain/dedicated_server/cpu.go
> +func NewCpu(quantity int32, Type string) Cpu {
Need to change int32 everywhere else then. That should be 15m work max, for another PR.

2024-08-20 14:51 UTC, majidkarimizadeh commented on internal/core/domain/dedicated_server/feature_availability.go
> +package dedicated_server
let's have a call and discuss more about it

2024-08-20 15:10 UTC, imtiazPabel commented
Along with package name, I think we should also follow the standard about the methods name as well. Like `dedicatedServer.all() / dedicatedServer.new() not dedicatedServer.dedicatedServerAll()/dedicatedServer.dedicatedServerNew()`

https://go.dev/blog/package-names
https://go.dev/doc/effective_go#package-names

2024-08-21 11:37 UTC, majidkarimizadeh commented on internal/core/domain/dedicated_server/port.go
> +	Port string
I checked the actual response, port is string!

2024-08-21 12:24 UTC, majidkarimizadeh commented on internal/provider/data_sources/dedicated_server/dedicated_servers/schema.go
> +											Computed:    true,
I'll remove all desc

2024-08-21 12:26 UTC, majidkarimizadeh commented on internal/repositories/dedicated_server_repository/data_adapters/to_domain_entity/adapter_test.go
> +	pciCard1 := dedicatedServer.NewPciCard()
as discussed, we're fine

2024-08-21 14:47 UTC, alrayyes requested changes

2024-08-21 14:47 UTC, alrayyes commented on internal/core/domain/dedicated_server/dedicated_server_test.go
> +		rack,
This way it's easy to use the got/want pattern as well. `want := domain.DedicatedServer{rack: domain.Rack{id: "rackId"}}` will work

2024-08-21 14:47 UTC, alrayyes commented on internal/provider/data_sources/dedicated_server/dedicated_servers/schema.go
> +func networkInterfaceSchema() schema.SingleNestedAttribute {
Personally i put this in a separate file to keep the schema.go as small as possible. But this is fine as well.

2024-08-21 14:47 UTC, alrayyes commented on internal/repositories/dedicated_server_repository/data_adapters/to_domain_entity/adapter.go
>  	dedicatedServer := domain.NewDedicatedServer(
This can be replaced with

```go
return domain.NewDedicatedServer(
		sdkDedicatedServer.GetId(),
		sdkDedicatedServer.GetAssetId(),
		sdkDedicatedServer.GetSerialNumber(),
		adaptRack(sdkDedicatedServer.GetRack()),
		adaptLocation(sdkDedicatedServer.GetLocation()),
		adaptFeatureAvailability(sdkDedicatedServer.GetFeatureAvailability()),
		adaptContract(sdkDedicatedServer.GetContract()),
		adaptPorts(sdkDedicatedServer.GetPowerPorts()),
		adaptPrivateNetworks(sdkDedicatedServer.GetPrivateNetworks()),
		adaptNetworkInterfaces(sdkDedicatedServer.GetNetworkInterfaces()),
		adaptSpecs(sdkDedicatedServer.GetSpecs()),
	)}
```

2024-08-21 14:47 UTC, alrayyes commented on internal/repositories/dedicated_server_repository/data_adapters/to_domain_entity/adapter_test.go
> +	contract := dedicatedServer.NewContract()
I think the sdk has it's own `New*()` functions that you can use for this. That way you know that all required attributes are always set.

2024-08-21 14:47 UTC, alrayyes commented on internal/repositories/dedicated_server_repository/data_adapters/to_domain_entity/adapter_test.go
> +	want := domain.NewContract("id", "customer_id", "status", "ref", "sales")
Nice

2024-08-21 16:24 UTC, majidkarimizadeh commented on internal/core/domain/dedicated_server/private_network.go
> +	LinkSpeed int32
we are gonna change all `int`s, so I'd do that later

2024-08-21 16:32 UTC, majidkarimizadeh commented on internal/repositories/dedicated_server_repository/data_adapters/to_domain_entity/adapter_test.go
> +	contract := dedicatedServer.NewContract()
true, but for dedicated server we don't have the required fields in SDK yet.
https://github.com/Leaseweb/leaseweb-go-sdk/blob/main/dedicatedServer/model_contract.go#L57
will come later

2024-08-21 16:34 UTC, alrayyes commented on internal/repositories/dedicated_server_repository/data_adapters/to_domain_entity/adapter_test.go
> +	contract := dedicatedServer.NewContract()
Another reason for dedicated fields then :D

2024-08-21 16:37 UTC, alrayyes commented on internal/provider/data_sources/dedicated_server/dedicated_servers/schema.go
> +func networkInterfaceSchema() schema.SingleNestedAttribute {
I agree, it's fine for now.

2024-08-22 07:30 UTC, majidkarimizadeh commented on internal/facades/dedicated_server/data_adapters/to_data_source_model/adapter_test.go
> +func Test_adaptDedicatedServers(t *testing.T) {
I think we should get rid `_` in the tests.
https://go.dev/doc/tutorial/add-a-test
https://ieftimov.com/posts/testing-in-go-naming-conventions/

2024-08-22 07:39 UTC, alrayyes commented
From what I can tell the naming convention is using _ for private functions.

On Thursday, August 22nd, 2024 at 9:30 AM, Majid Karimizadeh ***@***.***> wrote:

> @majidkarimizadeh commented on this pull request.
>
> ---------------------------------------------------------------
>
> In [internal/facades/dedicated_server/data_adapters/to_data_source_model/adapter_test.go](https://github.com/Leaseweb/terraform-provider-leaseweb/pull/41#discussion_r1726505743):
>
>> +	assert.Equal(t, int32(2), got.Specs.Ram.Size.ValueInt32())
> +	assert.Equal(t, int32(1), got.Specs.Cpu.Quantity.ValueInt32())
> +	assert.Equal(t, "id1", got.Specs.Hdds[0].Id.ValueString())
> +	assert.Equal(t, "d", got.Specs.PciCards[0].Description.ValueString())
> +	assert.Equal(t, "chassis", got.Specs.Chassis.ValueString())
> +	assert.Equal(t, true, got.Specs.HardwareRaidCapable.ValueBool())
> +	assert.Equal(t, "cid", got.Contract.Id.ValueString())
> +	assert.Equal(t, "rid", got.Rack.Id.ValueString())
> +	assert.False(t, got.FeatureAvailability.IpmiReboot.ValueBool())
> +	assert.Equal(t, "rack", got.Location.Rack.ValueString())
> +	assert.Equal(t, "name1", got.PowerPorts[0].Name.ValueString())
> +	assert.Equal(t, "pid", got.PrivateNetworks[0].Id.ValueString())
> +	assert.Equal(t, "public", got.NetworkInterfaces.Public.Mac.ValueString())
> +}
> +
> +func Test_adaptDedicatedServers(t *testing.T) {
>
> I think we should get rid _ in the tests.
> https://go.dev/doc/tutorial/add-a-test
> https://ieftimov.com/posts/testing-in-go-naming-conventions/
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/Leaseweb/terraform-provider-leaseweb/pull/41#discussion_r1726505743), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AAD42VVDB4UTEK6HPW5MJ4LZSWHTDAVCNFSM6AAAAABMTYKP5OVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDENJTG4YTGNBUG4).
> You are receiving this because your review was requested.Message ID: ***@***.***>

2024-08-22 08:25 UTC, majidkarimizadeh commented on internal/core/domain/dedicated_server/network_interfaces_test.go
> +	port := NewPort("name", "1111")
I removed this test.

2024-08-22 14:35 UTC, majidkarimizadeh commented on internal/facades/dedicated_server/data_adapters/to_data_source_model/adapter_test.go
> +	assert.Equal(t, "id", got.Id.ValueString())
fixed for most cases

2024-08-23 06:33 UTC, alrayyes approved these changes
Looks good. A few small things that could be improved if you have the time.

2024-08-23 06:33 UTC, alrayyes commented on internal/core/domain/dedicated_server/cpu.go
> +	Quantity int32
int

2024-08-23 06:33 UTC, alrayyes commented on internal/core/domain/dedicated_server/dedicated_server_test.go
> +	assert.Equal(t, "id", server.Id)
Replace this with want/got if you have time.

2024-08-23 06:33 UTC, alrayyes commented on internal/core/domain/dedicated_server/dedicated_server_test.go
> +	server := NewDedicatedServer(
got

2024-08-23 06:33 UTC, alrayyes commented on internal/core/domain/dedicated_server/hdd.go
> +func NewHdd(id, Type, unit, performanceType string, amount int32, size float32) Hdd {
int32 / float32 => int / float

2024-08-23 06:33 UTC, alrayyes commented on internal/core/domain/dedicated_server/network_interfaces_test.go
> +	public := NetworkInterface{Mac: "public"}
got/want

2024-08-23 06:33 UTC, alrayyes commented on internal/core/domain/dedicated_server/pci_card_test.go
> +	assert.Equal(t, "description", fmt.Sprintf("%v", pciCard))
Better to add a seperate test for this: `TestPciCardString`

2024-08-23 06:33 UTC, alrayyes commented on internal/core/domain/dedicated_server/private_network.go
> +	LinkSpeed int32
int (just noting this down for future reference)

2024-08-23 06:33 UTC, alrayyes commented on internal/core/domain/dedicated_server/ram.go
> +func NewRam(size int32, unit string) Ram {
int

2024-08-23 06:33 UTC, alrayyes commented on internal/core/domain/dedicated_server/specs_test.go
> +		Cpu{Quantity: 1},
Nice!

2024-08-23 06:33 UTC, alrayyes commented on internal/core/domain/dedicated_server/specs_test.go
> +	want := Specs{
Nice!

2024-08-23 06:33 UTC, alrayyes commented on internal/facades/dedicated_server/data_adapters/to_data_source_model/adapter_test.go
> +	assert.Equal(t, int32(2), got.Ram.Size.ValueInt32())
want

2024-08-23 06:33 UTC, alrayyes commented on internal/facades/dedicated_server/data_adapters/to_data_source_model/adapter_test.go
> +	assert.Equal(t, "id", got.Id.ValueString())
got/want

2024-08-23 06:33 UTC, alrayyes commented on internal/facades/dedicated_server/data_adapters/to_data_source_model/adapter_test.go
> +	server1 := domain.NewDedicatedServer(
Better to create mocks for server1/server2

2024-08-23 06:39 UTC, majidkarimizadeh commented
@alrayyes will be fixed in upcoming PR

2024-08-23 06:39 UTC, merged