[WIP] feat: implement dedicated server operating systems data source
Leaseweb/terraform-provider-leaseweb pull request #44
Opened 2024-08-23 10:26 UTC by imtiazPabel

2024-08-26 14:04 UTC, alrayyes requested changes

2024-08-26 14:04 UTC, alrayyes commented on internal/repositories/dedicated_server_repository/dedicated_server_repository.go
> +			operatingSystems = append(operatingSystems, r.adaptOperatingSystem(sdkOperatingSystem))
It might be a better idea to create `AdaptOperatingSystems` 

https://github.com/Leaseweb/terraform-provider-leaseweb/blob/59b8f0e9208dd5196ac643c90a913256bcb67105/internal/repositories/public_cloud_repository/data_adapters/to_domain_entity/adapter.go#L234

https://github.com/Leaseweb/terraform-provider-leaseweb/blob/59b8f0e9208dd5196ac643c90a913256bcb67105/internal/facades/public_cloud/data_adapters/to_data_source_model/adapter.go#L11

2024-08-27 13:26 UTC, imtiazPabel commented on internal/facades/dedicated_server/data_adapters/to_data_source_model/adapter.go
> +		operatingSystems.OperatingSystems = append(operatingSystems.OperatingSystems, operatingSystem)
I don't think so

2024-08-27 13:36 UTC, imtiazPabel commented on internal/repositories/dedicated_server_repository/dedicated_server_repository.go
> +			operatingSystems = append(operatingSystems, r.adaptOperatingSystem(sdkOperatingSystem))
I think we've discussed on arun's PR about it

2024-08-27 14:21 UTC, closed without merging