Control Panels datasoruce
Leaseweb/terraform-provider-leaseweb pull request #45
Opened 2024-08-26 05:32 UTC by arunvarghe

- Add script to have control panels data source
- Unit test
- Acceptance test

2024-08-26 06:51 UTC, alrayyes requested changes
Good stuff, a few small issues

2024-08-26 06:51 UTC, alrayyes commented on Caddyfile
> -}
An accidental commit, we've all been there. Please revert this as it has nothing to do with the PR

2024-08-26 06:51 UTC, alrayyes commented on examples/data-sources/leaseweb_control_panels/data-source.tf
> +data "leaseweb_control_panels" "all" {}
Are there any other control panels? If there are the data source name needs to be more specific.

2024-08-26 06:51 UTC, alrayyes commented on internal/core/domain/dedicated_server/control_panel.go
> +	controlPanel := ControlPanel{
This can be replaces with

```go
return ControlPanel{
Id: id,
Name name,
}
```

2024-08-26 06:51 UTC, alrayyes commented on internal/core/domain/dedicated_server/control_panel_test.go
> +	controlPanel := NewControlPanel(
It's better to use the want/got pattern here:

```go
got := NewControlPanel("id", "name")
want := dedicated_server.ControlPanel(Id: "id", Name: "name")

assert.Equal(t, want, got)
```

2024-08-26 06:51 UTC, alrayyes commented on internal/core/domain/dedicated_server/control_panel_test.go
> +func Test_NewControlPanel(t *testing.T) {
When it comes to tests "public" function tests should be camelCase. So in this case `TestNewControlPanel`.
Only private functions should have an underscore. So `newControlPanel` would be `Test_newControlPanel`

2024-08-26 06:51 UTC, alrayyes commented on internal/core/domain/dedicated_server/control_panels.go
> +type ControlPanels []ControlPanel
Nice

2024-08-26 06:51 UTC, alrayyes commented on internal/core/ports/dedicated_server_repository.go
> +	// GetAllControlPanels Retrieve all control panels from the dedicated server api.
This should be a sentence as documentation is generated from the comment. So:

`// GetAllControlPanels retrieves all control panels from the dedicated_server api.`

Also try to keep naming consistent. If we use `dedicated_server` we should it everywhere.

2024-08-26 06:51 UTC, alrayyes commented on internal/core/ports/dedicated_server_service.go
> +	// GetAllControlPanels gets all control panels.
Here you got it right :-)

2024-08-26 06:51 UTC, alrayyes commented on internal/core/ports/dedicated_server_service.go
> +	// GetAllControlPanels gets all control panels.
No need for the pointer return here. `GetAllDedicatedServers(ctx context.Context) (domain.DedicatedServers, *errors.ServiceError)` with also accept `return nil, nil`

2024-08-26 06:51 UTC, alrayyes commented on internal/core/ports/dedicated_server_service.go
> +	// GetAllControlPanels gets all control panels.
I believe the following is also valid:

```go
dedicatedServers := DedicatedServers{}
if dedicatedServers == nil {
return true
}
// Returns true
```

2024-08-26 06:51 UTC, alrayyes commented on internal/core/services/dedicated_server/service.go
> +	return &controlPanels, nil
`return controlPanels, nil` should also be ok.

2024-08-26 06:51 UTC, alrayyes commented on internal/core/services/dedicated_server/service_test.go
>  func newRepositorySpy() repositorySpy {
There's not really a need for this in the tests, but it doesn't hurt.

2024-08-26 06:51 UTC, alrayyes commented on internal/core/services/dedicated_server/service_test.go
> +			want := domain.ControlPanels{
see, want got :-)

2024-08-26 06:51 UTC, alrayyes commented on internal/core/services/dedicated_server/service_test.go
> +			spy.controlPanels = want
See, there's no point in the `newRepositorySpy()` function. To keep tests simple you set attributes individually anyway. So you may as well do:

```go
spy := RepositorySpy{controlPanels: want}
```

This keeps the code more succinct and easier to read. I should have done this from the beginning as well.

2024-08-26 06:51 UTC, alrayyes commented on internal/core/services/dedicated_server/service_test.go
> +					controlPanels: domain.ControlPanels{
I don't understand the point of this.

2024-08-26 06:51 UTC, alrayyes commented on internal/facades/dedicated_server/data_adapters/to_data_source_model/adapter_test.go
> +	controlPanels := domain.ControlPanels{
There's no need for this amount of detail as `TestAdaptControlPanel` already tests the `adaptControlPanel` function. To keep the test code to the minimal it's recommended to use mocks:

```go
got := AdaptControlPanels(domain.ControlPanels{Id: "id"}

assert.Len(t, got.ControlPanels, 1)
assert.Equal(t, id, got.ControlPanels[0].Id.ValueString())
```

This way you won't have to update this function is `NewControlPanel` ever changes.

2024-08-26 06:51 UTC, alrayyes commented on internal/facades/dedicated_server/facade.go
> +// GetAllControlPanels retrieve all operating systems.
//GetAllControlPanels retrieves all control panels.

2024-08-26 06:51 UTC, alrayyes commented on internal/facades/dedicated_server/facade.go
>  // GetAllDedicatedServers retrieve all dedicated servers.
Typo here:

`// GetAllDedicatedServers retrieves all dedicated servers.`

2024-08-26 06:51 UTC, alrayyes commented on internal/facades/dedicated_server/data_adapters/to_data_source_model/adapter_test.go
> +func TestAdaptControlPanel(t *testing.T) {
The function name should be `Test_adaptControlPanel`

2024-08-26 06:51 UTC, alrayyes commented on internal/provider/data_sources/dedicated_server/control_panels/schema.go
> +							Description: "The name of the control panel",
I know this is copied from the api definitions, but descriptions like this are useless. `The name of the control panel` can be inferred by anyone with more than 2 brain cells. I think it's better not to include useless documentation like this at all (for the end user). That way if the user reads the generated markdownfile (s)he knows that everything in it is important.

2024-08-26 06:51 UTC, alrayyes commented on internal/repositories/dedicated_server_repository/data_adapters/to_domain_entity/adapter_test.go
> +	controlPanel := dedicatedServer.NewControlPanel()
This is why you need to set the fields as `required` in the api definitions. This constructor function is useless as it does nothing. If the fields in de api definitions are set to `required`

```json
 "controlPanels": {
        "description": "A list of control panels",
        "items": {
          "title": "controlPanel",
          "description": "A single control panel",
          "properties": {
            "id": {
              "description": "The unique ID of this control panel",
              "type": "string"
            },
            "name": {
              "description": "A human readable name describing the control panel",
              "type": "string"
            }
          },
          "required": ["id", "name"],
          "type": "object"
        },
        "type": "array"
      }
```

 this would then be:

`controlPanel := dedicatedServer.NewControlPanel("id", "name")

2024-08-26 06:51 UTC, alrayyes commented on internal/repositories/dedicated_server_repository/dedicated_server_repository.go
> +	pagination := shared.NewPagination(
Pagination, nice!

2024-08-26 06:51 UTC, alrayyes commented on internal/repositories/dedicated_server_repository/dedicated_server_repository.go
> +	pagination := shared.NewPagination(
Might be a good idea to implement threading (see how instances are retrieved). It won't be much faster but you can learn how it works.

2024-08-26 06:53 UTC, alrayyes commented
It also appears that you haven't enabled the git hooks :-). Run the following:

`pnpm i`

The current commit message also needs to be changed to adhere to [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/). In this case it should be something like `feat: implement dedicated_server control panels datasource`

2024-08-26 07:30 UTC, arunvarghe commented on internal/repositories/dedicated_server_repository/data_adapters/to_domain_entity/adapter_test.go
> +	controlPanel := dedicatedServer.NewControlPanel()
Should it be updated in api definition?

2024-08-26 08:41 UTC, imtiazPabel commented on examples/data-sources/leaseweb_control_panels/data-source.tf
> +data "leaseweb_control_panels" "all" {}
Last time we had the name of `leaseweb_dedicated_server_control_panels`. Shouldn't we keep the same name for maintaining the legacy?
 https://github.com/Leaseweb/terraform-provider-leaseweb/blob/v0.4.1/examples/data-sources/leaseweb_dedicated_server_control_panels/data-source.tf#L2

2024-08-26 08:48 UTC, imtiazPabel commented on internal/core/domain/dedicated_server/control_panel_test.go
> +func Test_NewControlPanel(t *testing.T) {
@alrayyes, it's called `PascalCase(TestNewControlPanel)`. Also, where it's specified that public/private functions should have different way of test method? 

I'm asking because of, I just found, the test method should be PascalCase.

2024-08-26 08:50 UTC, alrayyes commented on examples/data-sources/leaseweb_control_panels/data-source.tf
> +data "leaseweb_control_panels" "all" {}
@imtiazPabel So much other stuff has changed in the provider that we may as well adopt a tabula rasa attitude towards this. Current clients are going to have to update their schemas anyway.

I do think we should write down naming rules somewhere.

2024-08-26 08:54 UTC, alrayyes commented on internal/core/domain/dedicated_server/control_panel_test.go
> +func Test_NewControlPanel(t *testing.T) {
@imtiazPabel Thank you , that is correct. `PascalCase`. That's how goland generates tests for me. I'm assuming that that's the correct way. It also makes sense. Otherwise you will get nonsensical tests function names like `TestdoSomething` `TestcalculateSomething`.

The underscore rule is only for "private" functions.

![](https://i.imgflip.com/91f56a.jpg)

2024-08-26 08:57 UTC, imtiazPabel commented on examples/data-sources/leaseweb_control_panels/data-source.tf
> +data "leaseweb_control_panels" "all" {}
Well, I feel, it should be discussed within the team. Because of, I'm on the same phase. I maintain my data source as `leaseweb_dedicated_server_operating_systems`. In that case, one of us, should change the data source name to be on the same page.

2024-08-26 09:00 UTC, alrayyes commented on examples/data-sources/leaseweb_control_panels/data-source.tf
> +data "leaseweb_control_panels" "all" {}
We should all by using the same naming schema, I agree. Longer strings are annoying for the end user, but inconsistency is more annoying.

2024-08-26 09:01 UTC, alrayyes commented on internal/repositories/dedicated_server_repository/data_adapters/to_domain_entity/adapter_test.go
> +	controlPanel := dedicatedServer.NewControlPanel()
yes

2024-08-26 09:25 UTC, imtiazPabel commented on internal/core/domain/dedicated_server/control_panel_test.go
> +func Test_NewControlPanel(t *testing.T) {
@alrayyes, PascalCase also make sense to me. I'm wondering about the underscore case for the private function. It would be appreciated, instead of assuming, if you could be confirmed.

https://go.dev/doc/tutorial/add-a-test
https://quii.gitbook.io/learn-go-with-tests/go-fundamentals/select

Everywhere I looked, I only found PascalCase. While they may not provide an example for private functions, they also didn't mention that private function names should use underscore case.

I don't trust goland, because of, goland also suggest the package name, which isn't recommended by community.

2024-08-26 09:34 UTC, alrayyes commented on internal/core/domain/dedicated_server/control_panel_test.go
> +func Test_NewControlPanel(t *testing.T) {
Indeed, all of the examples given are for exported functions.

This isn't [jetbrains opinion](https://youtrack.jetbrains.com/issue/GO-5185):

> In my opinion, this is the expected behaviour for unexported functions. Anyway, IDE uses [go tests](https://github.com/cweill/gotests) for tests generation, so it can be changed only there.

2024-08-26 15:33 UTC, imtiazPabel commented on internal/core/ports/dedicated_server_repository.go
> +	// GetAllControlPanels Retrieve all control panels from the dedicated server api.
@alrayyes, which document is generated from the comment?

2024-08-26 16:34 UTC, alrayyes commented on internal/core/ports/dedicated_server_repository.go
> +	// GetAllControlPanels Retrieve all control panels from the dedicated server api.
https://pkg.go.dev/github.com/leaseweb/terraform-provider-leaseweb@v1.3.2-alpha#section-documentation.

You also see the documentation & examples when you hover over functions in the IDE.

2024-08-27 05:23 UTC, arunvarghe commented on internal/repositories/dedicated_server_repository/dedicated_server_repository.go
> +	pagination := shared.NewPagination(
as discussed, not required

2024-08-27 05:50 UTC, arunvarghe commented on internal/core/services/dedicated_server/service_test.go
> +					controlPanels: domain.ControlPanels{
actually it is not required

2024-08-27 06:32 UTC, alrayyes requested changes

2024-08-27 06:32 UTC, alrayyes commented on Caddyfile
The file is still in the commit.  But let's ignore this for now.

2024-08-27 06:32 UTC, alrayyes commented on internal/facades/dedicated_server/data_adapters/to_data_source_model/adapter_test.go
> +	assert.Equal(t, "name", got.ControlPanels[0].Name.ValueString())
There's no need to validate all fields, that's already done in `Test_adaptControlPanel`. To make this test more concise you could do something like:

```go
got := AdaptControlPanels(domain.ControlPanels{Id: "id"}}

assert.Len(t, got.ControlPanels, 1)
assert.Equal(t, "id", got.ControlPanels[0].Id.ValueString())
```

That way you also don't have to update this test every time `NewControlPanel` changes.

2024-08-27 06:32 UTC, alrayyes commented on internal/facades/dedicated_server/facade_test.go
> +func TestFacade_GetAllControlPanels(t *testing.T) {
Since `GetAllControlPanels` is an exported function, the test name should be `TestGetAllControlPanels`. If you right click on a function in goland you can generate tests automatically.

2024-08-27 06:32 UTC, alrayyes commented on internal/provider/data_sources/dedicated_server/control_panels/read.go
> +		resp.Diagnostics.AddError("Unable to read control panels", err.Error())
We should discuss this, but it makes sense for this to be `Unable to read dedicated_server_control_panels`, no?

2024-08-27 06:32 UTC, alrayyes commented on internal/repositories/dedicated_server_repository/dedicated_server_repository.go
> +		for _, sdkControlPanel := range result.GetControlPanels() {
It would make more sense here to implement an `AdaptControlPanels` function, which loops through the sdk control panels & calls `adaptControlPanel`.

2024-08-27 06:34 UTC, alrayyes commented
Looks good! Just one thing about the commits, they should be in present tense as it's easier to read. This will become important for the auto generated changelog & release notes in the future.

So `feat: fixed comments about test cases and documentation` should be `feat: fix comments about test cases and documentation`

2024-08-27 06:38 UTC, alrayyes commented
In commit messages `feat` should only be used for introducing new features to the code base. So it should be 'chore(docs): fix comments about test cases and documentation` or `docs: fix comments about test cases and documentation`. 

I recommend taking 10 minutes to go through the [conventional commits summary](https://www.conventionalcommits.org/en/v1.0.0/#summary). The reason i'm nitpicking this is that eventually we want to auto generate changelogs & release notes from the commit messages. This only works if the conventional commit standard is properly adhered to.

2024-08-28 06:46 UTC, alrayyes requested changes

2024-08-28 06:46 UTC, alrayyes commented on internal/core/domain/dedicated_server/control_panel.go
> +// NewControlPanel creates a new controlPanel with all supported values.
`// NewControlPanel creates ControlPanel.` if you want to be pedantic here and clickable links.

2024-08-28 07:06 UTC, alrayyes approved these changes

2024-08-28 07:13 UTC, merged