feat: implement dedicated_server_operating_systems data source
Leaseweb/terraform-provider-leaseweb pull request #49
Opened 2024-08-27 14:31 UTC by imtiazPabel

2024-08-27 14:47 UTC, alrayyes requested changes
Looks good! Some small issues.

2024-08-27 14:47 UTC, alrayyes commented on docs/data-sources/dedicated_server_operating_systems.md
> +subcategory: ""
Perhaps we should use this. No idea what it's for....

2024-08-27 14:47 UTC, alrayyes commented on internal/core/ports/dedicated_server_repository.go
> +	// GetAllDedicatedServers retrieve all dedicated_servers from the dedicated server api.
`// GetAllDedicatedServers retrieves all dedicated_servers from the dedicated server api.`

2024-08-27 14:47 UTC, alrayyes commented on internal/core/ports/dedicated_server_repository.go
> +	// GetAllOperatingSystems retrieve all operating systems from the dedicated server api.
`// GetAllOperatingSystems retrieves all operating systems from the dedicated server api.`

2024-08-27 14:47 UTC, alrayyes commented on internal/core/services/dedicated_server/service_test.go
> +			repoResponse := domain.OperatingSystems{{}, {}, {}}
I don't understand what the purpose of this test is.

2024-08-27 14:47 UTC, alrayyes commented on internal/facades/dedicated_server/data_adapters/to_data_source_model/adapter_test.go
> +		domain.NewOperatingSystem("id1", "name"),
No need for `NewOperatingSystem` here. That functionality is already tested in `Test_adaptOperatingSystem`. It's better to use mocks here, otherwise you will need to update this function every time `NewOperatingSystem` changes. I would do something like this:

```go
got := AdaptOperatingSystems(domain.OperatingSystems{{Id: "id"}})

assert.Len(t, got.OperatingSystems, 1)
assert.Equal(t, "id", got.OperatingSystems[0].Id.ValueString())
```

2024-08-27 14:47 UTC, alrayyes commented on internal/provider/dedicated_server_operating_systems_data_source_test.go
> +				Check: resource.ComposeAggregateTestCheckFunc(
Maybe test the length here?

2024-08-27 14:58 UTC, imtiazPabel commented on docs/data-sources/dedicated_server_operating_systems.md
> +subcategory: ""
This is generated by running `go generate` command, and it's have for rest of the other's data sources

2024-08-27 15:04 UTC, imtiazPabel commented on internal/core/services/dedicated_server/service_test.go
> +			repoResponse := domain.OperatingSystems{{}, {}, {}}
I'm going to remove this. Confusion, creates from there https://github.com/Leaseweb/terraform-provider-leaseweb/blob/main/internal/core/services/public_cloud/service_test.go#L235

2024-08-27 15:06 UTC, alrayyes commented on docs/data-sources/dedicated_server_operating_systems.md
> +subcategory: ""
That's true. I'm wondering what terraform uses `subcategory` for.

2024-08-27 15:09 UTC, imtiazPabel commented on internal/provider/dedicated_server_operating_systems_data_source_test.go
> +				Check: resource.ComposeAggregateTestCheckFunc(
Length of what?
It's tested the count of operating_systems, id & name as well.

2024-08-27 15:09 UTC, imtiazPabel commented on docs/data-sources/dedicated_server_operating_systems.md
> +subcategory: ""
IDK TBH

2024-08-27 15:12 UTC, alrayyes commented on internal/provider/dedicated_server_operating_systems_data_source_test.go
> +				Check: resource.ComposeAggregateTestCheckFunc(
You're right. Sorry, I glanced over that

2024-08-28 06:07 UTC, alrayyes requested changes
A few more small things. let's get this merged today!

2024-08-28 06:07 UTC, alrayyes commented on internal/facades/dedicated_server/data_adapters/to_data_source_model/adapter.go
> +func AdaptOperatingSystems(domainOs domain.OperatingSystems) (modelOs model.OperatingSystems) {
As this is an exported function it's probably a good idea to add a documentation. Yesterday I found out that links are auto generated if you implement the correct package name. So if you add the following:

`// AdaptOperatingSystems adapts public_cloud.OperatingSystems to model.OperatingSystems` the 2 packages should be clickable. The easiest way to see this in action is to install a trail version of Goland & hover over the function.

2024-08-28 06:07 UTC, alrayyes commented on internal/provider/data_sources/dedicated_server/operating_systems/configure.go
> +func (d *operatingSystemsDataSource) Configure(
This appears over and over again. We should refactor all the `Configure` functions to use one module as we 100% know for sure that we use the same client everywhere.

2024-08-28 06:07 UTC, alrayyes commented on internal/repositories/dedicated_server_repository/data_adapters/to_domain_entity/adapter.go
> +func AdaptOperatingSystem(sdkOs dedicatedServer.OperatingSystem) domain.OperatingSystem {
Does this have to be exported, or is it only used by `AdaptOperatingSystems`?

2024-08-28 06:07 UTC, alrayyes commented on internal/repositories/dedicated_server_repository/dedicated_server_repository.go
> +		for _, sdkOperatingSystem := range result.OperatingSystems {
Can we use  `AdaptOperatingSystems` here instead?

2024-08-28 06:32 UTC, imtiazPabel commented on internal/provider/data_sources/dedicated_server/operating_systems/configure.go
> +func (d *operatingSystemsDataSource) Configure(
I think, create a jira ticket and let's do it depends on priority.

2024-08-28 06:35 UTC, alrayyes commented on internal/provider/data_sources/dedicated_server/operating_systems/configure.go
> +func (d *operatingSystemsDataSource) Configure(
It should be difficult. Just write a `Configure` function and use it in every `Resource.Configure`. On the one hand nice to have, on the other hand it's pretty trivial to implement and will save time for everyone long term.

2024-08-28 06:42 UTC, imtiazPabel commented on internal/facades/dedicated_server/data_adapters/to_data_source_model/adapter.go
> +func AdaptOperatingSystems(domainOs domain.OperatingSystems) (modelOs model.OperatingSystems) {
Nothing is clickable from documentation, at least what I can see.
https://pkg.go.dev/github.com/leaseweb/terraform-provider-leaseweb@v1.4.2-alpha/internal/repositories/public_cloud_repository/data_adapters/to_domain_entity

It is clickable from method structure.

2024-08-28 06:49 UTC, alrayyes commented on internal/facades/dedicated_server/data_adapters/to_data_source_model/adapter.go
> +func AdaptOperatingSystems(domainOs domain.OperatingSystems) (modelOs model.OperatingSystems) {
It is clickable in Goland.

2024-08-28 06:50 UTC, imtiazPabel commented on internal/repositories/dedicated_server_repository/data_adapters/to_domain_entity/adapter.go
> +func AdaptOperatingSystem(sdkOs dedicatedServer.OperatingSystem) domain.OperatingSystem {
Of course, it is exported. I will add the line for documentation as well. 
It is used from there https://github.com/Leaseweb/terraform-provider-leaseweb/pull/49/files#diff-dcc5e6379464aec34ca27c956915dea8656445659b8e576f3e0817f2397dc89bR145

2024-08-28 07:07 UTC, alrayyes commented on internal/repositories/dedicated_server_repository/data_adapters/to_domain_entity/adapter.go
> +func AdaptOperatingSystem(sdkOs dedicatedServer.OperatingSystem) domain.OperatingSystem {
That's not what i mean. If it's only used by `AdaptOperatingSystems` it doesn't need to be exported.

2024-08-28 08:38 UTC, closed without merging