feat: implement dedicated_server_credential data source
Leaseweb/terraform-provider-leaseweb pull request #55
Opened 2024-09-04 07:09 UTC by imtiazPabel

Will discuss with `BareMetal` team about to define `required` fields on `api-defination`. If there comes changes on `api-defination`, will leave another commit accordingly.

2024-09-05 05:06 UTC, alrayyes requested changes
Good stuff, just don't use models in the repository :p

2024-09-05 05:06 UTC, alrayyes commented on internal/repositories/dedicated_server_repository/dedicated_server_repository.go
> +	domainCred := to_domain_entity.AdaptCredential(*sdkCred)
`AdaptCredential` should be passed as a parameter to the `New` function, see public_cloud_repository. This also makes testing easier.

2024-09-05 05:06 UTC, alrayyes commented on internal/core/ports/dedicated_server_service.go
> +	GetServerCredential(cred model.Credential, ctx context.Context) (*domain.Credential, *errors.ServiceError)
As I sate later one, the service should not know anything about models, only domain entities. The facade should handle all the necessary translations.

2024-09-05 05:06 UTC, alrayyes commented on internal/provider/data_sources/dedicated_server/credential/schema.go
> +			"password": schema.StringAttribute{
Maybe a good idea to set `Sensitive: true` here.

2024-09-06 10:01 UTC, imtiazPabel commented on internal/repositories/dedicated_server_repository/dedicated_server_repository.go
> +	domainCred := to_domain_entity.AdaptCredential(*sdkCred)
I'm not clear enough. Do you mean like this? https://github.com/Leaseweb/terraform-provider-leaseweb/blob/main/internal/repositories/dedicated_server_repository/dedicated_server_repository.go#L188

Also, please enlighten me with a few lines, how it helps during testing. Because, I didn't face any struggle on testing yet.

2024-09-07 09:08 UTC, alrayyes requested changes
Worlds are colliding!

2024-09-07 09:08 UTC, alrayyes commented on internal/core/shared/enum_utils/enum.go
> +func ConvertStringSliceToValues[T ~string](enumValues []T) []string {
Nice! I wouldn't also implement this in other enums where applicable and remove duplicate tests.

2024-09-07 09:08 UTC, alrayyes commented on internal/core/shared/enum_utils/enum.go
> +func ConvertStringSliceToValues[T ~string](enumValues []T) []string {
I thinks this also warrants an Example in the tests.

2024-09-07 09:08 UTC, alrayyes commented on internal/facades/dedicated_server/facade.go
> +func GetServerCredentialTypes() enum.CredentialTypes {
This should return domain entities or enums, only objects that the provider understands. For examples see the public_cloud facade. The provider should know nothing about domain entities or enums. If I did this incorrectly myself I apologize in advance.

2024-09-07 09:08 UTC, alrayyes commented on internal/provider/data_sources/dedicated_server/credential/schema.go
> +				Description: "The type of the credential. Valid options are " + facade.GetServerCredentialTypes().Markdown(),
Nice!

2024-09-11 16:16 UTC, closed without merging