[WIP] feat: implement notification setting bandwidth creation
Leaseweb/terraform-provider-leaseweb pull request #56
Opened 2024-09-06 08:31 UTC by arunvarghe

2024-09-07 09:36 UTC, alrayyes requested changes
Good stuff! A few small comments.

2024-09-07 09:36 UTC, alrayyes commented on internal/core/domain/dedicated_server/notification_setting_bandwidth.go
> +type Actions []Action
This should be in a separate file. The same goes for `Action`

2024-09-07 09:36 UTC, alrayyes commented on internal/core/domain/dedicated_server/notification_setting_bandwidth.go
> +func NewCreateNotificationSettingBandwidth(
I don't understand what the point of this is. A `New` function should always return a struct and not a pointer to a struct.

2024-09-07 09:36 UTC, alrayyes commented on internal/core/services/dedicated_server/service_test.go
> +		"service passes back notification setting bandwidth from repository while creating a notification setting bandwidth",
imho it's best to keep these descriptions succinct. We already know which service we're testing here and that we're testing `create`. It's better for the description to be something like `passed back notificationSetting from repository`.

2024-09-07 09:36 UTC, alrayyes commented on internal/core/services/dedicated_server/service_test.go
> +			assert.Equal(t, &want, got)
I would switch this around so it's easier to understand: `assert.Equal(t, want, *got)`.

2024-09-07 09:36 UTC, alrayyes commented on internal/core/services/dedicated_server/service_test.go
> +		"error from repository CreateNotificationSettingBandwidth bubbles up while creating a notification setting bandwidth",
Same here, succinct is better imho.

2024-09-07 09:36 UTC, alrayyes commented on internal/core/shared/enum/notification_setting_bandwidth_frequency.go
> +const (
Nice!

2024-09-07 09:36 UTC, alrayyes commented on internal/core/domain/dedicated_server/notification_setting_bandwidth.go
> +func NewCreateNotificationSettingBandwidth(
Now I see what you want to do here :-). it's better to implement an optional struct for optional fields. See `Instance` domain entity for an example. So the code would look something like:

```go
type Action struct {
RequiredField1 string
RequiredField2 int
OptionalField1 *string
OptionalField2 *int
}

type Optional struct {
OptionalField1 *string
OptionalField2 *int
}


func NewAction(requiredField1 string, requiredField2 int, optional Optional) Action {
action := Action{
RequiredField1: requiredField1,
RequiredField2: requiredField2,
}

if optional.OptionalField1 != nil {
action.OptionalField1 = optional.OptionalField1
}

if optional.OptionalField2 != nil {
action.OptionalField2 = optional.OptionalField2
}

return action
}

```

2024-09-07 09:36 UTC, alrayyes commented on internal/facades/dedicated_server/data_adapters/to_domain_entity/adapter_test.go
> +	t.Run("required values are set", func(t *testing.T) {
Missing test for optional fields.

2024-09-07 09:36 UTC, alrayyes commented on internal/provider/resources/dedicated_server/notification_setting_bandwidth/delete.go
> +func (n *notificationSettingBandwidthResource) Delete(
Is delete doing nothing a feature or are you just doing this because the interface is telling you to?

2024-09-07 09:36 UTC, alrayyes commented on internal/provider/resources/dedicated_server/notification_setting_bandwidth/read.go
> +) {
Same question as Delete

2024-09-07 09:36 UTC, alrayyes commented on internal/provider/resources/dedicated_server/notification_setting_bandwidth/schema.go
> +					stringvalidator.OneOf(facade.GetFrequencies()...),
Nice!

2024-09-07 09:36 UTC, alrayyes commented on internal/provider/resources/dedicated_server/notification_setting_bandwidth/update.go
> +func (n *notificationSettingBandwidthResource) Update(
Same question as Delete/Read :p

2024-09-07 09:36 UTC, alrayyes commented on internal/provider/resources/dedicated_server/notification_setting_bandwidth/validator/greater_than_zero_validator.go
> +type GreaterThanZeroValidator struct{}
I'm pretty sure there's already a built in terraform validator with the same functionality that you can use.

2024-09-07 09:36 UTC, alrayyes commented on internal/provider/resources/dedicated_server/notification_setting_bandwidth/validator/greater_than_zero_validator.go
> +type GreaterThanZeroValidator struct{}
Oooohhh, because it's a string. Nevermind, good work!

2024-09-07 09:36 UTC, alrayyes commented on internal/provider/resources/dedicated_server/notification_setting_bandwidth/validator/greater_than_zero_validator_test.go
> +	t.Run("does not set errors if the value is greater than 0", func(t *testing.T) {
I like these tests!

2024-09-09 07:53 UTC, arunvarghe commented on internal/provider/resources/dedicated_server/notification_setting_bandwidth/delete.go
> +func (n *notificationSettingBandwidthResource) Delete(
Yes, right!!, As we discussed in last refinement, will do delete, read and update as different story

2024-09-09 10:27 UTC, arunvarghe commented on internal/provider/resources/dedicated_server/notification_setting_bandwidth/read.go
> +) {
Yes, right!!, I just did this because the interface makes it mandatory. As we discussed in the last refinement, will do delete, read and update as different story

2024-09-09 10:27 UTC, arunvarghe commented on internal/provider/resources/dedicated_server/notification_setting_bandwidth/update.go
> +func (n *notificationSettingBandwidthResource) Update(
Yes, right!!, I just did this because the interface makes it mandatory. As we discussed in the last refinement, will do delete, read and update as different story

2024-09-10 10:07 UTC, alrayyes requested changes
Still a few things. Could you please see if there's maybe an interfaces that just expects `Create` to exist. If not the functions that need to be implemented should have `fatal` in them so they don't silently fail imho.

2024-09-10 10:07 UTC, alrayyes commented on internal/provider/resources/dedicated_server/notification_setting_bandwidth/delete.go
> +func (n *notificationSettingBandwidthResource) Delete(
Ok. I could be wrong but I'm pretty sure that there are other interfaces you can implement where `Delete` isn't mandatory. Correct me if i'm wrong.

2024-09-10 10:07 UTC, alrayyes commented on internal/repositories/dedicated_server_repository/data_adapters/to_domain_entity/value_adapters_test.go
> +func TestAdaptNullableStringToValue(t *testing.T) {
I would also add an `ExampleAdaptNullableStringToValue` test here as this function is exported and meant to be re used.

2024-09-10 10:08 UTC, alrayyes commented on examples/resources/leaseweb_dedicated_server_notification_setting_bandwidth/resource.tf
> +  unit      = "Gbps"
If these are already enums please feel free to ignore my comments. Are they also set as enums in the api specifications?

2024-09-12 13:15 UTC, closed without merging